name: covid19_tracker
description: An app to provide real-time tally of  COVID-19 patients in India.
version: 1.4.2+1


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  http: ^0.12.0+2
  intl: ^0.16.1
  fl_chart: ^0.9.0
  intro_views_flutter: ^2.8.0
  flutter_icons: ^1.1.0
  url_launcher: ^5.4.5
  dynamic_theme: ^1.0.0
  shared_preferences: ^0.5.7
  package_info: ^0.4.0+17

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - lang/en-US.json
    - lang/hi-IN.json
    - assets/


  fonts:
    - family: Stalemate
      fonts:
        - asset: fonts/Stalemate-Regular.ttf
    - family: QuicksandMedium
      fonts:
        - asset: fonts/Quicksand-Medium.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Regular.otf
